### PR TITLE
Swift 3.0 migration

### PR DESCRIPTION
**Pull request by UberJason**
Hey,

I work at Capital One Labs. I was volunteering at CalHacks this weekend and noticed the Nessie iOS SDK was still on Swift 2.3. I've gone ahead and migrated it to 3.0 and it seems like it works.

### CODE REVIEW

**Comment by borikanes** [comment]
@UberJason we know who you are. We are very aware of who you are, we know you're at calhacks too. We even know where you live.
ok JK
On a serious note though, do you think we should totally stop supporting 2.3 or we should give them an option of both 3 and 2.3 in case some people still are for some reason writing in 2.3? Or should we just not care

**Comment by UberJason** [comment]
@borikanes Haha. :P I think you should stop supporting 2.3. It's just going to confuse people who are new to Swift; 3.0 is the default in Xcode 8 and most pods are on 3 now, so just doing 3.0 is much simpler.

**Comment by borikanes** [comment]
Ok cool. I'll merge it after the hackathons this weekend. there are 4 going on this weekend and i need to update the [website](http://api.reimaginebanking.com/sdks). But I don't wanna redeploy while people are using the API.  
If there are people that want to use it this weekend though maybe we should add a link to your branch in the README?

**Comment by UberJason** [comment]
Yup the update after hackathons makes sense, and sure, we can link to it - don't think anyone this weekend is going to use it though, not at this point when we're more than halfway through the hackathon!

**Comment by borikanes** [comment]
Thanks for helping to make the migration

**Comment by UberJason** [comment]
Yeah dude, I didn't know who was in charge of it, but I should've guessed! ;)

**Comment by caryz** [comment]
Hi Jason, thanks for making the PR 😄 

So Apple is dropping support for Swift 2.3 after Xcode 8.2 (see [deprecations](https://developer.apple.com/library/prerelease/content/releasenotes/DeveloperTools/RN-Xcode/Introduction.html)). With that in mind, I think we should have a 2.3 branch (current `master`) in archive to support those who still want to use 2.3 until Xcode 8.3 rolls around. `swift-3.0` will become the main `master` branch. For now, I shall test with the `swift-3.0` branch before making the swap-aroo, sound good 👍 ?

**Comment by UberJason** [comment]
@caryz If I'm understanding you correctly, you're suggesting that master will reflect the swift-3.0 work, while the previous version of master (still in 2.3) will remain around as a side branch until 2.3 is deprecated fully? If so, that makes sense to me.

**Comment by caryz** [comment]
@UberJason Yep that is exactly right, I'm just testing the changes with @victorralov before merging it in. But you should be good, when I looked into the migration I basically had the same changes as your diff 😄

**Comment by VictorRLV** [comment]
@UberJasono Thanks a lot! We'll test this and merge it as soon as possible!

**Comment by caryz** [comment]
LGTM 👍 , merging.

Side Note: we still need to update the TestProject's accountId's lol.

**Pull request merged**
