### PR TITLE
Support Loans

### PR DESCRIPTION
**Pull request by UberJason**
I've updated the SDK to support the Loans endpoint. Get loans by accountId, get loan by loanId, create loan, update loan, delete loan.

Also, the view controller used as the test harness is now a stack view with all the buttons, rather than a scroll view with manually-created constraints for all the buttons - hope that's cool. Was easier than inserting my button. Consequently, the project now requires iOS 9.0+, which seems 100% fine for a hackathon.

### CODE REVIEW

**Comment by UberJason** [comment]
@borikanes lol?

**Comment by borikanes** [comment]
@UberJason don't even pay attention to this. Act like I didn't just merge this please. Embarrassing.....

**Comment by UberJason** [comment]
@borikanes I mean as long as you're finally doing maintenance here, you should also merge my other PR from 3 years ago where I converted this into a Cocoapods compatible library. Although by now maybe it should just move straight to SPM 😛

**Comment by borikanes** [comment]
Yes I was about to create an issue for SPM. Thanks for the PRs!!

**Pull request merged**
